In [24]:
from scipy.stats import norm
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from scipy import stats
import math

In [3]:
# Punto 1

miu = 502
gramos = np.array([506,508,499,503,504,510,497,512])
print(gramos)

gramos_2 = np.array([514,505,493,496,506,502,509,496])
print(gramos_2)

[506 508 499 503 504 510 497 512]
[514 505 493 496 506 502 509 496]


In [4]:
mean1 = gramos.mean()
mean2 = gramos_2.mean()
dev1 = gramos.std()
dev2 = gramos_2.std()
print(mean1)
print(mean2)

504.875
502.625


In [13]:
# Punto 2
aspirina_gramos = np.array([98,102,104,98,100,102,96])
n = 7
miu = 99
aspirina_mean = aspirina_gramos.mean()
print(aspirina_mean)
aspirina_std = np.std(aspirina_gramos, ddof=1)
print(aspirina_std)
estadistico = (aspirina_mean - miu)/(aspirina_std/np.sqrt(n))
print(estadistico)



100.0
2.8284271247461903
0.9354143466934853


In [21]:
# Punto 3

mean_engineer = 22.74
mean_BM = 27.23
std_engineer = 2.99
std_BM = 3.06
n1=10
n2 =14

# eL ESTADISTICO DE PRUEBA PARA UNA HIPOTESIS DE LAS VARIANZAS POBLACIONALES ES: Sx^2/Sy^2

EP = (std_engineer**2)/(std_BM**2)
print(f" El estadistico de prueba es {EP}")

# La region de rechazo es F _(nx-1,ny-1)

# Define your parameters:
probability = 0.9  # The cumulative probability (e.g., for a 95% confidence level)
dfn = n1-1             # Numerator degrees of freedom (df1)
dfd = n2-1            # Denominator degrees of freedom (df2)

# Calculate the F value (critical value)
f_value_1 = stats.f.ppf(q=probability, dfn=dfn, dfd=dfd)

print(f" El valor del punto de la zona max de rechazo es {f_value_1}")

probability2 = 0.1  # The cumulative probability (e.g., for a 95% confidence level)
dfn2 = n1-1             # Numerator degrees of freedom (df1)
dfd2 = n2-1            # Denominator degrees of freedom (df2)

# Calculate the F value (critical value)
f_value_2 = stats.f.ppf(q=probability2, dfn=dfn2, dfd=dfd2)

print(f" El valor del punto de la zona min de rechazo es {f_value_2}")

 El estadistico de prueba es 0.9547716690161905
 El valor del punto de la zona max de rechazo es 2.1638195794408634
 El valor del punto de la zona min de rechazo es 0.42300973084088556


In [23]:
mean1 = 7.42
mean2 = 6.87
a = 0
var1=1.25
var2=0.97
n1=36
n2=32
sp=np.sqrt(((n1-1)*var1+(n2-1)*var2)/(n1+n2-2))

EP2 = (mean1-mean2-a)/(sp*np.sqrt(1/n1+1/n2))
print(EP2)

probability = 0.975  # The accumulated probability (e.g., for a 95% confidence interval, this is for one tail)
df = n1+n2-2
# Get the t-value (critical value)
t_value = stats.t.ppf(probability, df)
print(t_value)



2.140520640713412
1.9965644189523113


In [29]:
# Punto 1

a = 416
miu_maq = 502
maq_1 = np.array([409,421,417,412,415,417,413,410,419,416])
print(maq_1)

maq_2 = np.array([415,420,413,409,423,419,411])
print(maq_2)

mean_m1 = maq_1.mean()
mean_m2 = maq_2.mean()
dev_m1 = np.std(maq_1, ddof=1)
dev_m2 =  np.std(maq_2, ddof=1)
n1 = len(maq_1)
n2 = len(maq_2)

estadistico_m = (mean_m1 - a)/(dev_m1/np.sqrt(n1))
print(estadistico_m)

from scipy.stats import norm

alpha = 0.975
# Calcula el cuantil (Z-score)
z_score = norm.ppf(alpha)

print(z_score)
# Resultado aproximado:

[409 421 417 412 415 417 413 410 419 416]
[415 420 413 409 423 419 411]
-0.8984790706936133
1.959963984540054


In [31]:
# Punto 4

# eL ESTADISTICO DE PRUEBA PARA UNA HIPOTESIS DE LAS VARIANZAS POBLACIONALES ES: Sx^2/Sy^2

EP = (dev_m1 **2)/(dev_m2 **2)
print(EP)

# Define your parameters:
probability = 0.95  # The cumulative probability (e.g., for a 95% confidence level)
dfn = n1-1             # Numerator degrees of freedom (df1)
dfd = n2-1            # Denominator degrees of freedom (df2)

# Calculate the F value (critical value)
f_value_maq = stats.f.ppf(q=probability, dfn=dfn, dfd=dfd)
print(f" El valor del punto de la zona max de rechazo es {f_value_maq}")

0.5712643678160919
 El valor del punto de la zona max de rechazo es 4.099015541716521
