In [1]:
import numpy as np

A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)

(3, 2)


In [2]:
U, S, VT = np.linalg.svd(A) # Desempaquetar las matrices de rotación y escalamiento
print(f"U: {U}") #
print(f"S: {S}") # Vector con los valores de la diagonal
print(f"VT: {VT}") # Sus columnas son los eigevectores de la matriz A^T.A

U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S: [9.52551809 0.51430058]
VT: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [7]:
Sigma = np.zeros(A.shape)

Sigma[:len(S), :len(S)] = np.diag(S)
print(Sigma)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [10]:
A_reconstruida = U @ Sigma @ VT
print(A_reconstruida)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [14]:
# SISTEMA DE CALIFICACION DE 0.0 A 5.0 PARA TRES PELICULAS (DUNE, SHREK, LOS CASA FANTASMAS)
patron_scifi = np.array([5,1,4]) # calificacion de tres peliculas de usuario con gusto de ciencia ficcion
patron_comedia = np.array([1,5,3]) # calificacion de tres peliculas de usuario con gusto de comedia

A_signal = np.array([patron_scifi, patron_comedia, patron_scifi *0.5 + patron_comedia*0.5, patron_scifi *0.8 + patron_comedia*0.2])

print(A_signal)

[[5.  1.  4. ]
 [1.  5.  3. ]
 [3.  3.  3.5]
 [4.2 1.8 3.8]]


In [19]:
ruido = np.random.randn(4,3)*0.3 # agregar ruido a la señal

A_ruidosa = A_signal + ruido
print(A_ruidosa)

[[4.88059606 0.73086401 3.66586156]
 [0.35356812 5.16368413 3.09211975]
 [2.94535602 2.85934349 3.32144288]
 [4.14587693 1.80798979 4.34615948]]


In [20]:
U, S, VT = np.linalg.svd(A_ruidosa)
print(np.round(S,2))

[10.91  4.71  0.42]


In [30]:
k = 3

U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

A_filtrada = U_k @ S_k @ VT_k
print(np.round(A_filtrada,2))

[[4.88 0.73 3.67]
 [0.35 5.16 3.09]
 [2.95 2.86 3.32]
 [4.15 1.81 4.35]]


In [31]:
print(A_signal)

[[5.  1.  4. ]
 [1.  5.  3. ]
 [3.  3.  3.5]
 [4.2 1.8 3.8]]
