In [17]:
import numpy as np

# Dimension 0

escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


In [6]:
# Dimension 1

vector =  np.array([30,29,35,31,33,36,43])
print(vector)
print(type(vector))

[30 29 35 31 33 36 43]
<class 'numpy.ndarray'>


In [10]:
# Dimension 2

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
print(type(matriz))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [14]:
# Dimension >3

tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)
print(type(tensor))

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [16]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
diag = np.diag([1,2,3])
print(diag)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [22]:
random = np.random.random((2,3))
print(random)

[[0.03452689 0.89923155 0.78297069]
 [0.45414223 0.15066295 0.7596313 ]]
