In [7]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])
print(array[1:3])


20
50
[20 30]


In [11]:
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [12]:
index = [2,3,4]
print(array[index])

[30 40 50]


In [18]:
array = np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,2])

[[5 2 4]
 [5 8 1]
 [6 4 7]]
4


In [19]:
print(array[:2,:2])

[[5 2]
 [5 8]]
