In [2]:
import numpy as np
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices*discount
print(discount_prices)

[ 90. 180. 270.]


In [6]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[270 287 378]
 [380 461 143]
 [143 323 481]]
[[280 307 408]
 [390 481 173]
 [153 343 511]]


In [9]:
array = np.array([1,2,3,4,5])
print(np.all(array>2))
print(np.any(array>4))

False
True


In [11]:
array_a= np.array([1,2,3])
array_b= np.array([4,5,6])
concatenated = np.concatenate((array_a,array_b))
print(concatenated)

[1 2 3 4 5 6]


In [14]:
stack_v = np.vstack((array_a,array_b))
print(stack_v)

[[1 2 3]
 [4 5 6]]


In [15]:
stack_h = np.hstack((array_a,array_b))
print(stack_h)

[1 2 3 4 5 6]


In [19]:
array_c = np.arange(1,10)
split_array = np.split(array_c,3)
print(split_array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
