In [ ]:
import numpy as np

# Supongamos que tenemos la variable 'respuestas' con las opiniones de los clientes
respuestas = np.array(['bueno', 'excelente', 'malo', 'bueno', "malo",'excelente', 'bueno', "bueno",'malo', 'excelente',"excelente","excelente"])

# Utilizamos el método unique para encontrar los elementos únicos
elementos_unicos = np.unique(respuestas)
print(elementos_unicos)

['bueno' 'excelente' 'malo']


In [ ]:
unique_elements, counts = np.unique(respuestas, return_counts=True)
print(unique_elements)
print(counts)


['bueno' 'excelente' 'malo']
[4 5 3]


In [ ]:
array_x = np.arange(10)
view_y = array_x[1:3]
array_x[1:3] = [10,11]
print(array_x)
print(view_y)


[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [ ]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


In [16]:
array_x = np.arange(10)