In [2]:
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed = matrix.T
print(matrix)
print(transposed)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
array = np.arange(1,13)
reshaped_array = array.reshape(2,6)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
reverse = array[::-1]
print(reverse)

[12 11 10  9  8  7  6  5  4  3  2  1]


In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_matrix = matrix.flatten()
print(matrix)
print(flattened_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
