In [2]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [4]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [5]:
double_array = np.array([1,2,3], dtype= "d")
print(double_array)

[1. 2. 3.]


In [6]:
z = z.astype(np.float64)
print(z)

3.0


In [16]:
sum = np.sum(array)
print(f"the sum is {sum}")

mean = np.mean(array)
print(f"the mean is {mean}")

desv_stan =np.std(array)
print(f"the standar deviation is {desv_stan}")

the sum is 21
the mean is 3.5
the standar deviation is 1.707825127659933


In [5]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


In [7]:
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


In [9]:
trans_A = A.T
print("Transpuesta de A:", trans_A)

Transpuesta de A: [[1 3]
 [2 4]]


In [10]:
inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [12]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]
