In [2]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
print(A)
print(B)
print(C)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [3]:
# Multiplicacion

product = np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


In [5]:
# Determinantes e Inversa
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(det_A)
print(inv_A)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
# Resolver sistema de ecuaciones Ax = b

b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)



[-7.  8.]
