In [2]:
import numpy as np
import pandas as pd
# CSV
path = '/content/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin1')

# EXCEL
#date_excel = pd.read_excel(path)

#JSON
#data_json = pd.read_json(path)

print(retail_data.head())
print(type(retail_data))

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom  
<class 'pandas.core.frame.DataFrame'>


In [ ]:
data_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

dt_from_array = pd.DataFrame(data_2,columns=['A','B','C'])
print(data_2)
print(dt_from_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
data_3 = [[1, 'Jhon',22],[2,'Ana',24 ]]
de_from_list = pd.DataFrame(data_3, columns=['ID','Name','Age'])
print(de_from_list)

   ID  Name  Age
0   1  Jhon   22
1   2   Ana   24


In [ ]:
data_4 = [{"ID":1,'Name': 'Jhon', 'Age': 22},{"ID":2,'Name': 'Ana', 'Age': 24}]
dt_from_list_dict = pd.DataFrame(data_4)
print(dt_from_list_dict)

   ID  Name  Age
0   1  Jhon   22
1   2   Ana   24


In [ ]:
data_5 = {"ID":[1,2,3],'Name': ['Jhon','Ana','Mike'], 'Age': [22,24,21]}
dt_from_dict = pd.DataFrame(data_5)
print(dt_from_dict)

   ID  Name  Age
0   1  Jhon   22
1   2   Ana   24
2   3  Mike   21


In [ ]:
data_6 = {"ID":pd.Series([1,2,3]),'Name':pd.Series(['Jhon','Ana','Mike']), 'Age': pd.Series([22,24,21])}
dt_from_series_dict = pd.DataFrame(data_6)
print(dt_from_series_dict)

   ID  Name  Age
0   1  Jhon   22
1   2   Ana   24
2   3  Mike   21


In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/Online_Retail.csv'

Mounted at /content/drive


In [ ]:
column_names = retail_data.columns
print(column_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')


In [ ]:
numpy_rows, numpy_columns = retail_data.shape
print(f"Numero de filas: {numpy_rows}")
print(f"Numero de columnas: {numpy_columns}")

Numero de filas: 541909
Numero de columnas: 8


In [ ]:
daily_sales = retail_data['Quantity'] #Guarda toda la columna de 'Quantity' en una nueva variable
print(daily_sales)
print(daily_sales[2]) #Imprime el resultado de la fila 3

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64
8


In [ ]:
summary = retail_data.describe()
print(summary)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000


In [ ]:
mean_value = daily_sales.mean()
print(f"la media es {mean_value}")
median_value = daily_sales.median()
print(f"la mediana es {median_value}")
sum_value = daily_sales.sum()
print(f"la suma total es {sum_value}")
count_value = daily_sales.count()
print(f" el conteo total es {count_value}")

la media es 9.55224954743324
la mediana es 3.0
la suma total es 5176450
 el conteo total es 541909


In [ ]:
retail_data.head(8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/10 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/10 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/10 8:28,1.85,17850.0,United Kingdom


In [ ]:
first_row = retail_data.iloc[0]
print(first_row)

InvoiceNo                                  536365
StockCode                                  85123A
Description    WHITE HANGING HEART T-LIGHT HOLDER
Quantity                                        6
InvoiceDate                          12/1/10 8:26
UnitPrice                                    2.55
CustomerID                                17850.0
Country                            United Kingdom
Name: 0, dtype: object


In [ ]:
first_five_rows = retail_data.iloc[0:5]
print(first_five_rows)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom  


In [ ]:
subset = retail_data.iloc[:3, :2]
print(subset)

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B


In [ ]:
value_2row_3column = retail_data.iloc[1, 2]
print(value_2row_forthcolumn)

WHITE METAL LANTERN


In [ ]:
row_index_0_4 = retail_data.loc[:4]
print(row_index_0_4)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom  


In [ ]:
quantity_column = retail_data.loc[:, 'Quantity']
print(quantity_column)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64


In [ ]:
quantity_2column = retail_data.loc[:, ['Quantity','UnitPrice']]
print(quantity_2column)

        Quantity  UnitPrice
0              6       2.55
1              6       3.39
2              8       2.75
3              6       3.39
4              6       3.39
...          ...        ...
541904        12       0.85
541905         6       2.10
541906         4       4.15
541907         4       4.15
541908         3       4.95

[541909 rows x 2 columns]


In [3]:
retail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


In [5]:
retail_data["InvoiceDate"] = pd.to_datetime(retail_data["InvoiceDate"])
retail_data.info()

/tmp/ipykernel_388/1320699599.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  retail_data["InvoiceDate"] = pd.to_datetime(retail_data["InvoiceDate"])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
