In [2]:
import numpy as np
from numpy import random
from numpy import linalg as ln

In [6]:
a = [1,2,3,4,5]
b= [1,2,3,4,5]

print(f"List addition: {a+b }")


a = np.array(a)
b = np.array(b)
c = a +1.5
a_max =print(f"numpy Max: {np.max(a) }")
print(f"Numpy addition: {a+b }")
print(c)
print(a_max)
print(type(a))
a_list = a.tolist()  # Convert np.ndarray back to list

print(a == b)

List addition: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy Max: 5
Numpy addition: [ 2  4  6  8 10]
[2.5 3.5 4.5 5.5 6.5]
None
<class 'numpy.ndarray'>
[ True  True  True  True  True]


In [7]:
print("Sum:", a + b)

print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b)


Sum: [ 2  4  6  8 10]
Difference: [0 0 0 0 0]
Product: [ 1  4  9 16 25]
Quotient: [1. 1. 1. 1. 1.]


In [9]:
matrix = np.array([[3,1],[0,2]])
print(matrix)

eig_values,eig_vectors = np.linalg.eig(matrix)
print(eig_values)
print(eig_vectors)

[[3 1]
 [0 2]]
[3. 2.]
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]
